spring:
  datasource:
    url: jdbc:mysql://localhost:3306/author_book
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo=
  expiration: 600000

